name: Build and push Docker image
on:
  push:
    paths:
      - 'shinyproxy/Chart.yaml'
jobs:
  docker:
    - uses: actions/checkout@v2
    - uses: mikefarah/yq@v4.9.6
    - name: Get Shinyproxy version
      id: version
      run: echo "::set-output name=shinyproxy_version::$(yq eval '.appVersion' shinyproxy/Chart.yaml)"
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v2
      with:
        context: images
        build-args: [SHINYPROXY_VERSION=${{ steps.version.outputs.shinyproxy_version }}]
        tags: ${{ steps.version.outputs.shinyproxy_version }}
